import React from 'react';
import Head from 'next/head'

import Waves from '@/components/canvas/waves';

import { DynamicIsland, MusicPlayer } from '@/components/dynamicIsland';
import { DynamicIslandSize } from '@/components/dynamicIsland/DynamicIsland';
import { Header, Aside } from '@/components/layout';
import { HeroSection, AboutSection, SkillsSection } from '@/components/sections';
import { useGeolocation } from '@/hooks';


export default function Home() {

  const [dynamicState, setDynamicState] = React.useState<DynamicIslandSize>('compact');

  const Geolocation = useGeolocation()

  console.log(Geolocation);

  return (
    <>
      <Head>
        <title>Buzatu Danyel - Digitize your idea</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen overflow-hidden scroll-smooth bg-[#191919]">
        <Header className='fixed inset-x-0 py-10 z-10'>
          <DynamicIsland
            state={dynamicState}
            onHover={() => setDynamicState('ultra')}
            onLeave={() => setDynamicState('compact')}
          >
            <MusicPlayer size={dynamicState} />
          </DynamicIsland>
        </Header>
        <Aside />
        <div className='relative'>
          <HeroSection />
          <AboutSection />
          <SkillsSection />
          <footer className='relative flex h-screen bg-gradient-to-t from-[#283E51] to-transparent snap-center'>
            <div className='absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-10 opacity-80'>
              <div className='[--gradient-length:10] [--gradient-interval-size:3] GradientProvider' style={{ "--gradient-progress": 1 } as React.CSSProperties}>
                <h1 className='flex flex-col font-black text-transparent bg-clip-text leading-[1.2] [--font-scale:0.100] SectionHello GradientProvider_Diagonal'>
                  <span>Whats your sine?</span>
                </h1>
              </div>
            </div>
            <Waves pointSize={15} distance={5} speed={1.7} height={4} />
          </footer>
        </div>
      </div>
    </>
  )
}

