import Head from 'next/head'
import { motion } from "framer-motion"
import { Canvas } from '@react-three/fiber';
import Waves from '@/components/waves';
import { RubberBand } from '@/animation/RubberBand';
import { useEffect, useState } from 'react';


export default function Home() {

  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.5
      }
    }
  }

  const fadeDown = {
    hidden: { opacity: 0, x: -20 },
    show: { opacity: 1, x: 0, transition: { type: "spring" } },
  };

  const [clientWindowHeight, setClientWindowHeight] = useState(0);

  const handleScroll = () => {
    setClientWindowHeight(window.scrollY);
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  });

  console.log(clientWindowHeight)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-full bg-gradient-to-b from-[#283E51] to-transparent">
        <header className='fixed w-full mx-auto flex justify-center'>
          <nav className='flex gap-x-10 mt-16'>
            <a href='#' className='font-semibold leading-6 tracking-wider uppercase'>Home</a>
            <a href='#projects' className='font-semibold leading-6 tracking-wider uppercase'>Projects</a>
            <a href='#' className='font-semibold leading-6 tracking-wider uppercase'>Contact</a>
          </nav>
        </header>
        <Canvas camera={{ position: [0, 10, 100], fov: 60 }}>
          <Waves />
        </Canvas>
        <div className='absolute top-0 h-full container flex justify-center items-center'>
          <motion.div
            initial="hidden"
            animate="show"
            variants={container}
          >
            <motion.span variants={fadeDown} className='text-7xl font-bold tracking-wider flex flex-row'>
              {"Hi".split("").map((value, index) => (
                <RubberBand key={index}>{value}</RubberBand>
              ))}
            </motion.span>
            <motion.span variants={fadeDown} className='text-7xl font-bold tracking-wider flex flex-row'>
              {"Im Danyel".split("").map((value, index) => (
                <RubberBand key={index}>{value === " " ? "\u00A0" : value}</RubberBand>
              ))}
              {"\u00A0"}
              {"Buzatu".split("").map((value, index) => (
                <RubberBand key={index}><span className='text-[#eb4a4c]'>{value}</span></RubberBand>
              ))}
            </motion.span>
            <motion.span variants={fadeDown} className='text-7xl font-bold tracking-wider flex flex-row'>
              {"Creative Developer".split("").map((value, index) => (
                <RubberBand key={index}>{value === " " ? "\u00A0" : value}</RubberBand>
              ))}
            </motion.span>
          </motion.div>
        </div>
        <main className='relative h-full container flex justify-center items-center' id='projects'>
          <motion.div
            initial="hidden"
            animate="show"
            variants={container}
          >
            <motion.span variants={fadeDown} className='text-7xl font-bold tracking-wider flex flex-row'>
              {"Hi".split("").map((value, index) => (
                <RubberBand key={index}>{value}</RubberBand>
              ))}
            </motion.span>
            <motion.span variants={fadeDown} className='text-7xl font-bold tracking-wider flex flex-row'>
              {"Im Danyel".split("").map((value, index) => (
                <RubberBand key={index}>{value === " " ? "\u00A0" : value}</RubberBand>
              ))}
              {"\u00A0"}
              {"Buzatu".split("").map((value, index) => (
                <RubberBand key={index}><span className='text-[#eb4a4c]'>{value}</span></RubberBand>
              ))}
            </motion.span>
            <motion.span variants={fadeDown} className='text-7xl font-bold tracking-wider flex flex-row'>
              {"Creative Developer".split("").map((value, index) => (
                <RubberBand key={index}>{value === " " ? "\u00A0" : value}</RubberBand>
              ))}
            </motion.span>
          </motion.div>
        </main>
      </div>
    </>
  )
}
